name: Deploy to VM

on:
  workflow_run:
    workflows: ["Bustopia CI"]      # must match the `name:` in ci.yml
    types: [ completed ]

jobs:
  deploy:
    # run only if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Add the SSH key so we can connect
      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      # Run deploy script on the VM
      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no seed@172.167.170.46 \
              "bash ~/SWE/Bustopia/deploy.sh"

      # Frontend basic test
      - name: Verify frontend is up (homepage test)
        run: |
          echo "Waiting for frontend to start..."
          sleep 10
          curl -k --fail --retry 5 --retry-delay 5 https://172.167.170.46:3000/

      # Wait for backend to be ready
      - name: Wait for backend health check
        run: |
          echo "Waiting for Spring Boot backend to be fully ready..."
          for i in {1..30}; do
            echo "Attempt $i/30: Checking backend health..."
            if curl -k -f -s https://172.167.170.46:8443/actuator/health > /dev/null 2>&1; then
              echo "✅ Backend is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Backend failed to start within 5 minutes"
              exit 1
            fi
            echo "⏳ Backend not ready yet, waiting 10 seconds..."
            sleep 10
          done

      # Smoke-test the running backend
      - name: Verify backend is up (ping test)
        run: |
          curl -k --fail https://172.167.170.46:8443/api/ping
