name: Bustopia CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: fiihad/bustopia-backend
  IMAGE_FRONTEND: fiihad/bustopia-frontend

jobs:
# ──────────────────────────────────────────────
# 1. Backend unit tests  (Maven)
# ──────────────────────────────────────────────
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"         # change if you use 17/11/8

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Maven tests
        working-directory: "BusTopia Backend"
        run: mvn -B test

# ──────────────────────────────────────────────
# 2. Build images (no push yet)
# ──────────────────────────────────────────────
  build-images:
    needs: backend-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./BusTopia Backend
          push: false                  # build only
          tags: ${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Bustopia FrontEnd
          push: false
          tags: ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}

# ──────────────────────────────────────────────
# 3. Integration smoke-tests using those images
# ──────────────────────────────────────────────
  integration-tests:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Start backend container
        run: |
          docker run -d --name backend -p 8080:8080 \
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}
          # wait up to 30 s for Spring to boot
          for i in {1..15}; do
            if curl --silent http://localhost:8080/api/ping; then exit 0; fi
            sleep 2
          done
          echo "Backend ping failed"; docker logs backend; exit 1

      - name: Start frontend container
        run: |
          docker run -d --name frontend -p 3001:80 \
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
          # very light homepage check
          curl --fail --retry 5 --retry-delay 3 http://localhost:3001/

      - name: Clean up
        if: always()
        run: docker rm -f backend frontend

# ──────────────────────────────────────────────
# 4. Push images to Docker Hub (only if all tests passed)
# ──────────────────────────────────────────────
  push-images:
    needs: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend + latest tag
        run: |
          docker tag ${{ env.IMAGE_BACKEND }}:${{ github.sha }} \
                     ${{ env.IMAGE_BACKEND }}:latest
          docker push --all-tags ${{ env.IMAGE_BACKEND }}

      - name: Push frontend + latest tag
        run: |
          docker tag ${{ env.IMAGE_FRONTEND }}:${{ github.sha }} \
                     ${{ env.IMAGE_FRONTEND }}:latest
          docker push --all-tags ${{ env.IMAGE_FRONTEND }}
